### ISSUE TITLE
Daemon Logs

### ISSUE THREAD

**Issue by aalvrz** [jcurry/ZenPacks.skills1st.LDAPMonitoring#1]
Hi Jane.

I am trying to implement a ZenPack Daemon and I am using this ZenPack as reference. However I am having trouble finding any of the logs in my daemon when using `log.info`, `log.debug`, etc...

When I start the daemon, a log file is created in the directory $ZENHOME/log with many log messages that probably come from other components used in the daemon python file. None of the logs I send appear anywhere.

Would appreciate any insight.

**Comment by jcurry** [comment]
You will only get debug and info messages if you are running the daemon 
with debugging turned on.  To test, can you run your daemon in the 
foreground with full debug eg.

zenMyDaemon run -v 10

Assuming it is a standard daemon, it should have an etc file in 
$ZENHOME/etc and you could change the logseverity in there to 20 (debug) 
and restart the daemon normally.  This probably generates more stuff 
than you want for normal production but it is good while testing.

The other trick - and not sure that it will work with a custom daemon - 
is to use the debug flag on the daemon.  For example with a standard, 
zencommand daemon, you can run:
zencommand debug
to toggle debug logging on the running daemon.  A second zencommand 
debug sets the logging level back to normal.

Cheers,
Jane

On 17/11/15 05:38, Jaime Alvarez wrote:

> I Jane.
> 
> I am trying to implement a ZenPack Daemon and I am using this ZenPack 
> as reference. However I am having trouble finding any of the logs in 
> my daemon when using |log.info|, |log.debug|, etc...
> 
> When I start the daemon, a log file is created in the directory 
> $ZENHOME/log with many log messages that probably come from other 
> components used in the daemon python file. None of the logs I send 
> appear anywhere.
> 
> Would appreciate any insight.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.skills1st.LDAPMonitoring/issues/1.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by jcurry** [comment]
Sorry - the logseverity should be 10 for debug - 20 is normal.
Cheers,
Jane

On 17/11/15 08:25, Jane Curry wrote:

> You will only get debug and info messages if you are running the 
> daemon with debugging turned on.  To test, can you run your daemon in 
> the foreground with full debug eg.
> 
> zenMyDaemon run -v 10
> 
> Assuming it is a standard daemon, it should have an etc file in 
> $ZENHOME/etc and you could change the logseverity in there to 20 
> (debug) and restart the daemon normally.  This probably generates more 
> stuff than you want for normal production but it is good while testing.
> 
> The other trick - and not sure that it will work with a custom daemon 
> - is to use the debug flag on the daemon.  For example with a 
>   standard, zencommand daemon, you can run:
>   zencommand debug
>   to toggle debug logging on the running daemon.  A second zencommand 
>   debug sets the logging level back to normal.
> 
> Cheers,
> Jane
> 
> On 17/11/15 05:38, Jaime Alvarez wrote:
> 
> > I Jane.
> > 
> > I am trying to implement a ZenPack Daemon and I am using this ZenPack 
> > as reference. However I am having trouble finding any of the logs in 
> > my daemon when using |log.info|, |log.debug|, etc...
> > 
> > When I start the daemon, a log file is created in the directory 
> > $ZENHOME/log with many log messages that probably come from other 
> > components used in the daemon python file. None of the logs I send 
> > appear anywhere.
> > 
> > Would appreciate any insight.
> > 
> > —
> > Reply to this email directly or view it on GitHub 
> > https://github.com/jcurry/ZenPacks.skills1st.LDAPMonitoring/issues/1.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by aalvrz** [comment]
Jane thank you for your fast response.

When I install and re-install the ZenPack using  `zenpack --link --install $ZP_DIR`, no config file is generated whatsoever in `$ZENHOME/etc`,even when the daemon configuration has the line `CFGFILE=$CFGDIR/$DAEMON_NAME.conf`

Because of this, I created the config file myself and pasted the output of the command `<daemon_name> genconfig`. Is this ok to do?

**Comment by jcurry** [comment]
It should be OK.  Did your new daemon appear in the GUI under ADVANCED 
-> Daemons?  You may find, if it does, that changing parameters there 
will then generate the file.

Fundamentally, it is just a text file.  If it doesn't exist, defaults 
will be used, including logseverity=20 (info).

Cheers,
Jane

On 18/11/15 01:30, Jaime Alvarez wrote:

> Jane thank you for your fast response.
> 
> When I install and re-install the ZenPack using |zenpack --link 
> --install $ZP_DIR|, no config file is generated whatsoever in 
> |$ZENHOME/etc|,even when the daemon configuration has the line 
> |CFGFILE=$CFGDIR/$DAEMON_NAME.conf|
> 
> Because of this, I created the config file myself and pasted the 
> output of the command |<daemon_name> genconfig|. Is this ok to do?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.skills1st.LDAPMonitoring/issues/1#issuecomment-157568083.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by aalvrz** [comment]
Yes I can see it in the GUI, thank you so much for your help Jane.
